### ISSUE TITLE
Claroshop API

### ISSUE THREAD

**Issue by edgarjoao** [Gergab00/sellercontrol-node-v1#2]
Hola @Gergab00,
Gracias por compartir tu código, me ha sido de mucha ayuda. Sabes donde puedo encontrar la información del API de claroshop?

Saludos!

**Comment by Gergab00** [comment]
Hola @edgarjoao para la informacion de la API te tienes que registrar como vendedor de Claroshop y hay un correo de sistemas, ahi te dan un PDF donde viene toda la informacion al respecto
